apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: go-app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: go-app-container
        image: abeerseada/go-app
        ports:
        - containerPort: 8080
        