apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  namespace: go-app-namespace
spec:
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort  # Exposes the Service on a port accessible outside Mini