apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: python-app-namespace
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort  # Exposes the Service on a port accessible outside Mini