apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  namespace: node-app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: node-app-container
        image: abeerseada/node-app
        ports:
        - containerPort: 8080
