apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: node-app-namespace
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort  # Exposes the Service on a port accessible outside Mini