apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-mongo-app-deployment
  namespace: node-mongo-app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-mongo-app
  template:
    metadata:
      labels:
        app: node-mongo-app
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: node-mongo-app-container

        image: abeerseada/node-mongo-app
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: mongodb://mongo-service:27017/testdb