  apiVersion: v1
  kind: Service
  metadata:
    name: mongo-service
    namespace: node-mongo-app-namespace
  spec:
    selector:
      app: mongo
    ports:
      - protocol: TCP
        port: 27017       # Port exposed by the service
        targetPort: 27017 # Port on the MongoDB container
    type: NodePort 