apiVersion: v1
kind: Service
metadata:
  name: node-mongo-app-service
  namespace: node-mongo-app-namespace
spec:
  selector:
    app: node-mongo-app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: NodePort